"""Keep type-start rules and native cases in sync with the Rust prelude."""

import os
from pathlib import Path
import re
import subprocess
import sys
import unittest


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))
import type_cases
import type_inventory


class TypeInventoryTests(unittest.TestCase):
    def test_inventory_matches_prelude(self):
        expected = type_inventory.inventory()
        self.assertEqual(type_inventory.from_prelude(type_inventory.PRELUDE.read_text()), expected)
        if executable := os.environ.get("VIBES"):
            live = subprocess.check_output([executable, "prelude"], text=True)
            self.assertEqual(type_inventory.from_prelude(live), expected)

    def test_extraction_uses_type_positions_not_names_or_values(self):
        prelude = '''
# imaginary is not a type
class collection<T: ordered>
  def method<U: comparable>(field: record<string, item>, mode: :symbol_value, label: string = "value") -> result?
  def shape -> { key: scalar, nested: [left, right] }
end
type alias_type = scalar | union_member
type NamedAlias = named_member
'''
        self.assertEqual(type_inventory.from_prelude(prelude), {
            "builtins": sorted("collection ordered comparable record string item result scalar left right alias_type union_member named_member".split()),
            "generics": {"collection": 1, "record": 2},
        })

    def test_generated_variables_and_syntax_cases_are_current(self):
        types = type_inventory.inventory()
        syntax = (ROOT / "Vibescript.sublime-syntax").read_text()
        start = syntax.index("  # Generated by scripts/type_inventory.py")
        end = syntax.index("  trailing_keyword:", start)
        self.assertEqual(syntax[start:end], type_inventory.variable_block(types))
        self.assertEqual((ROOT / "tests/syntax_test_type_inventory.vibe").read_text(), type_cases.render(types))

    def test_all_type_start_discriminators_share_the_inventory(self):
        syntax = (ROOT / "Vibescript.sublime-syntax").read_text()
        for context, variable in [("typed-local", "annotation_start"), ("type-literals", "generic_type"),
                                  ("type-literals", "shape_literal_start"), ("block-parameter-type", "type_start"),
                                  ("shape-field-type", "shape_field_type_start"),
                                  ("literal-type-expression", "literal_type_name"),
                                  ("literal-type-elements", "type_start")]:
            block = syntax.split("\n  " + context + ":\n", 1)[1]
            block = re.split(r"\n  \S", block, maxsplit=1)[0]
            self.assertIn("{{" + variable + "}}", block, context)
        variables = dict(re.findall(r"^  (\w+): '(.*)'$", syntax.split("\ncontexts:", 1)[0], re.MULTILINE))

        def pattern(name):
            value = "{{" + name + "}}"
            while "{{" in value:
                value = re.sub(r"{{(\w+)}}", lambda match: "(?:" + variables[match[1]] + ")", value)
            return re.compile(value.replace("''", "'"))

        for name in type_inventory.inventory()["builtins"]:
            for ending in (" = value", "? = value", " | string = value"):
                self.assertIsNotNone(pattern("annotation_start").match(name + ending), name)
            for key in ("field", "field?", '"quoted key"', "'single key'"):
                value = "nil | int" if name == "nil" else name
                self.assertIsNotNone(pattern("shape_literal_start").match(f"{{ {key}: {value} }}"), name)
        for name in type_inventory.inventory()["generics"]:
            self.assertIsNotNone(pattern("generic_type").fullmatch(name))
        for value in ("[int, string]", "(int) -> bool", "() -> bool", "{ field?: int, ... }"):
            self.assertIsNotNone(pattern("type_start").match(value))
            self.assertIsNotNone(pattern("annotation_start").match(value))
        self.assertIsNotNone(pattern("shape_literal_start").match("{ ... }"))
        self.assertIsNone(pattern("shape_field_type_start").match("nil }"))
        for value in ("numbered", "integer", "String", "unrecognized"):
            self.assertIsNone(pattern("builtin_type").fullmatch(value))


if __name__ == "__main__":
    unittest.main()
